// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarInput: typeof import('./src/components/AvatarInput.vue')['default']
    BaseInput: typeof import('./src/components/forms/BaseInput.vue')['default']
    BaseSelect: typeof import('./src/components/forms/BaseSelect.vue')['default']
    ChangeAccountFormCard: typeof import('./src/components/cards/ChangeAccountFormCard.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    EmployeeConnectCard: typeof import('./src/components/cards/EmployeeConnectCard.vue')['default']
    EmployeeFormModal: typeof import('./src/components/modals/EmployeeFormModal.vue')['default']
    EmployeeInfoCard: typeof import('./src/components/cards/EmployeeInfoCard.vue')['default']
    FacultyFormModal: typeof import('./src/components/modals/FacultyFormModal.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeiEditFormModal: typeof import('./src/components/modals/HeiEditFormModal.vue')['default']
    HelloI18n: typeof import('./src/components/HelloI18n.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HorizontalNav: typeof import('./src/components/HorizontalNav.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LocaleSwitcher: typeof import('./src/components/LocaleSwitcher.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    Pagination: typeof import('./src/components/partials/Pagination.vue')['default']
    RightSidebar: typeof import('./src/components/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    SubmitButton: typeof import('./src/components/buttons/SubmitButton.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
    UpdateHeiFormModal: typeof import('./src/components/modals/UpdateHeiFormModal.vue')['default']
    UserProfileDropdown: typeof import('./src/components/dropdowns/UserProfileDropdown.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
